# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
$username\
[@](green bold)\
$hostname\
[ on ](blue)\
$os\
$shell\
$all\
"""

### ALTERNATE prompt format ###
# format = """
# [â•­â”€userâ”€â”€â”€â¯](bold blue) $username
# [â”£â”€systemâ”€â¯](bold yellow) $hostname
# [â”£â”€projectâ¯](bold red) $directory$rust$git_branch$git_state$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs
# [â•°â”€cmdâ”€â”€â”€â”€â¯](bold green)
# """

### OLD prompt format ### 
# format = """\
# [â•­â•´](blue)\
# $all\
# $fill\
# $os\
# $shell\
# $line_break\
# [â•°â”€](blue)\
# $character"""

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ—](bold red)"

[fill]
symbol = " "

[os]
disabled = false

[os.symbols]
Arch = "[ïŒƒ](green) "
Debian = "î½ "
Fedora = "ïŒŠ "
Ubuntu = "ïŒ› "
Windows = "î˜ª "

[shell]
disabled = false
powershell_indicator = "pwsh"
bash_indicator = "[bash](green)"

# Shows the username
[username]
style_user = "yellow bold"
style_root = "root bold"
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](bold yellow)'
disabled = false

[directory]
truncation_length = 4
truncation_symbol = "â€¦/"
home_symbol = "î˜— ~"
read_only_style = "197"
read_only = " ï€£ "
format = "[in](blue) [$path]($style)[$read_only]($read_only_style) "

# ï¡ - alternate git branch logo
[git_branch]
symbol = "î‚  "
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = ".../"
style = "bold green"

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "bold green"
conflicted = "ğŸ³"
up_to_date = "ï† "
untracked = "ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ó°“œ "
modified = "ï„ "
staged = '[++\($count\)](green)'
renamed = "î«  "
deleted = "ï€” "

[docker_context]
format = "via [î° $context](bold blue) "

[python]
symbol = "îœ¼ "

[rust]
symbol = "î¨ "

[java]
symbol = "îœ¸ "

[golang]
symbol = "îœ¤ "

[lua]
symbol = "î˜  "

[nodejs]
format = "via [îœ˜ $version](bold green) "

[ruby]
format = "via [îœ¹ $version]($style) "

[kubernetes]
format = 'on [ó±ƒ¾ $context\($namespace\)](bold purple) '
disabled = false

[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"
